### ISSUE TITLE
find out how to populate stage / test environments with test data

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/workflow-archiver-job#21]
presumably there's a way to create completed workflows that are ready to be archived ... in a stage environment.

Either by doing something to druids in that environment, OR by creating table entries.

@blalbrit may know the magic.

**Comment by tallenaz** [comment]
This is documented here https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/workflow-archiver-job/operations-concerns.md
